apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc-2
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.name }}