apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-tester-argocd-app-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/falbocubbit/argocd-plays.git
    targetRevision: HEAD
    path: manifests/app-1
  destination:
    server: https://kubernetes.default.svc #'cause we are running argo in the destination cluster
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true