apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-devops
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-apps
    repoURL: 'https://github.com/falbocubbit/argocd-plays.git'
    targetRevision: HEAD
    directory:
      exclude: '*.disabled'
  sources: []
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: false
      selfHeal: true
